// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 3.4
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_fade(c,a,b){var e=jQuery;var d=e("ul",b);var f={position:"absolute",left:0,top:0,width:"100%",height:"100%"};this.go=function(g,h){var i=e(a.get(g)).clone().css(f).hide().appendTo(b);if(!c.noCross){var j=e(a.get(h)).clone().css(f).appendTo(b);d.hide();j.fadeOut(c.duration,function(){j.remove()})}i.fadeIn(c.duration,function(){d.css({left:-g+"00%"}).show();i.remove()});return g}};// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 3.4
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container1").wowSlider({effect:"fade",prev:"",next:"",duration:36*100,delay:22*100,width:1060,height:596,autoPlay:true,playPause:false,stopOnHover:false,loop:false,bullets:0,caption:false,captionEffect:"slide",controls:false,onBeforeStep:0,images:[{src:"./1_0029.jpg",title:"1_0029"},{src:"./1_0026.jpg",title:"1_0026"},{src:"./1_0024.jpg",title:"1_0024"},{src:"./1_0016.jpg",title:"1_0016"},{src:"./1_0025.jpg",title:"1_0025"},{src:"./1_0027.jpg",title:"1_0027"},{src:"./1_0013.jpg",title:"1_0013"},{src:"./1_0018.jpg",title:"1_0018"},{src:"./1_0023.jpg",title:"1_0023"},{src:"./1_0014.jpg",title:"1_0014"},{src:"./1_0011.jpg",title:"1_0011"},{src:"./1_0003.jpg",title:"1_0003"},{src:"./1_0004.jpg",title:"1_0004"},{src:"./1_0007.jpg",title:"1_0007"},{src:"./1_0001.jpg",title:"1_0001"},{src:"./1_0010.jpg",title:"1_0010"},{src:"./1_0002.jpg",title:"1_0002"},{src:"./1_0008.jpg",title:"1_0008"},{src:"./1_0009.jpg",title:"1_0009"},{src:"./1_0019.jpg",title:"1_0019"},{src:"./1_0012.jpg",title:"1_0012"},{src:"./1_0015.jpg",title:"1_0015"},{src:"./1_0021.jpg",title:"1_0021"},{src:"./1_0022.jpg",title:"1_0022"}]});